version: '2'
services:
  mongo:
    image: mongo:3.6.5-jessie
    container_name: mongo-pepit
    ports:
    - "27017:27017"
    volumes:
    - ${PWD}/data/mongo:/data/db
    restart: always
  fake-s3:
    image: lphoward/fake-s3
    container_name: fake-s3-pepit
    ports:
    - "4569:4569"
    volumes:
    - /tmp:/fakes3_root
  redis:
    image: redis:4.0.9-alpine
    container_name: redis-pepit
    command: ["redis-server", "--appendonly", "yes"]
    ports:
    - "6379:6379"
    volumes:
    - ${PWD}/data/redis:/data
    restart: always